"""add pending_cve_news_link table

Revision ID: 49a42993a600
Revises: 3f14807f3ed2
Create Date: 2026-09-21 18:03:25.254651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a42993a600'
down_revision: Union[str, Sequence[str], None] = '3f14807f3ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_cve_news_link',
    sa.Column('cve_news_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cve_news_id'], ['cve_news.id'], ),
    sa.PrimaryKeyConstraint('cve_news_id', 'cve_id')
    )
    op.create_index('ix_pending_cve_news_link_cve_id', 'pending_cve_news_link', ['cve_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pending_cve_news_link_cve_id', table_name='pending_cve_news_link')
    op.drop_table('pending_cve_news_link')
    # ### end Alembic commands ###
