"""add embedding columns to cve and cve_news

Revision ID: 62e7f27319ee
Revises: 49a42993a600
Create Date: 2026-10-05 17:30:55.505022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "62e7f27319ee"
down_revision: Union[str, Sequence[str], None] = "49a42993a600"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cve",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
    )
    op.add_column(
        "cve_news",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cve_news", "embedding")
    op.drop_column("cve", "embedding")
    # ### end Alembic commands ###
